[package]
name = "pcurve-p256"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
pcurve-uint = { path = "../../uint-field" }
pcurve-field = { path = "../../field" }
curve = { path = "../../curve" }
bigint = "4"