(function() {var implementors = {};
implementors["bigint"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bigint/uint/struct.U128.html\" title=\"struct bigint::uint::U128\">U128</a>",synthetic:true,types:["bigint::uint::U128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bigint/uint/struct.U256.html\" title=\"struct bigint::uint::U256\">U256</a>",synthetic:true,types:["bigint::uint::U256"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"bigint/uint/struct.U512.html\" title=\"struct bigint::uint::U512\">U512</a>",synthetic:true,types:["bigint::uint::U512"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"bigint/uint/enum.FromDecStrErr.html\" title=\"enum bigint::uint::FromDecStrErr\">FromDecStrErr</a>",synthetic:true,types:["bigint::uint::FromDecStrErr"]},];
implementors["byteorder"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"byteorder/enum.BigEndian.html\" title=\"enum byteorder::BigEndian\">BigEndian</a>",synthetic:true,types:["byteorder::BigEndian"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"byteorder/enum.LittleEndian.html\" title=\"enum byteorder::LittleEndian\">LittleEndian</a>",synthetic:true,types:["byteorder::LittleEndian"]},];
implementors["ng_curve"] = [{text:"impl&lt;C&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_curve/struct.AffinePoint.html\" title=\"struct ng_curve::AffinePoint\">AffinePoint</a>&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;C as <a class=\"trait\" href=\"ng_curve/trait.Curve.html\" title=\"trait ng_curve::Curve\">Curve</a>&gt;::<a class=\"type\" href=\"ng_curve/trait.Curve.html#associatedtype.Value\" title=\"type ng_curve::Curve::Value\">Value</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ng_curve::affine::Point"]},{text:"impl&lt;C&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_curve/struct.JacobianPoint.html\" title=\"struct ng_curve::JacobianPoint\">JacobianPoint</a>&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;C as <a class=\"trait\" href=\"ng_curve/trait.Curve.html\" title=\"trait ng_curve::Curve\">Curve</a>&gt;::<a class=\"type\" href=\"ng_curve/trait.Curve.html#associatedtype.Value\" title=\"type ng_curve::Curve::Value\">Value</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ng_curve::jacobian::Point"]},];
implementors["ng_field"] = [{text:"impl&lt;F&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_field/struct.FieldElement.html\" title=\"struct ng_field::FieldElement\">FieldElement</a>&lt;F&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;F as <a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt;::<a class=\"type\" href=\"ng_field/trait.Field.html#associatedtype.Value\" title=\"type ng_field::Field::Value\">Value</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ng_field::element::FieldElement"]},{text:"impl&lt;F&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_field/struct.MontgomeryElement.html\" title=\"struct ng_field::MontgomeryElement\">MontgomeryElement</a>&lt;F&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;F as <a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt;::<a class=\"type\" href=\"ng_field/trait.Field.html#associatedtype.Value\" title=\"type ng_field::Field::Value\">Value</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ng_field::mont::MontgomeryElement"]},];
implementors["ng_p256"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_p256/struct.P256Field.html\" title=\"struct ng_p256::P256Field\">P256Field</a>",synthetic:true,types:["ng_p256::P256Field"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_p256/struct.P256Curve.html\" title=\"struct ng_p256::P256Curve\">P256Curve</a>",synthetic:true,types:["ng_p256::P256Curve"]},];
implementors["ng_polynomial"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_polynomial/struct.Polynomial.html\" title=\"struct ng_polynomial::Polynomial\">Polynomial</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ng_polynomial::Polynomial"]},];
implementors["ng_secp256k1"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_secp256k1/struct.Secp256k1Field.html\" title=\"struct ng_secp256k1::Secp256k1Field\">Secp256k1Field</a>",synthetic:true,types:["ng_secp256k1::Secp256k1Field"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_secp256k1/struct.Secp256k1Curve.html\" title=\"struct ng_secp256k1::Secp256k1Curve\">Secp256k1Curve</a>",synthetic:true,types:["ng_secp256k1::Secp256k1Curve"]},];
implementors["ng_uint"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ng_uint/struct.U256.html\" title=\"struct ng_uint::U256\">U256</a>",synthetic:true,types:["ng_uint::U256"]},];
implementors["rustc_hex"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"rustc_hex/enum.FromHexError.html\" title=\"enum rustc_hex::FromHexError\">FromHexError</a>",synthetic:true,types:["rustc_hex::FromHexError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
