(function() {var implementors = {};
implementors["bigint"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U128.html\" title=\"struct bigint::uint::U128\">U128</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U128.html\" title=\"struct bigint::uint::U128\">U128</a>",synthetic:false,types:["bigint::uint::U128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U256.html\" title=\"struct bigint::uint::U256\">U256</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U256.html\" title=\"struct bigint::uint::U256\">U256</a>",synthetic:false,types:["bigint::uint::U256"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U512.html\" title=\"struct bigint::uint::U512\">U512</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U512.html\" title=\"struct bigint::uint::U512\">U512</a>",synthetic:false,types:["bigint::uint::U512"]},];
implementors["ng_curve"] = [{text:"impl&lt;I:&nbsp;<a class=\"trait\" href=\"ng_field/arith/trait.Scalar.html\" title=\"trait ng_field::arith::Scalar\">Scalar</a>, C:&nbsp;<a class=\"trait\" href=\"ng_curve/trait.Curve.html\" title=\"trait ng_curve::Curve\">Curve</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;I&gt; for <a class=\"struct\" href=\"ng_curve/struct.AffinePoint.html\" title=\"struct ng_curve::AffinePoint\">Point</a>&lt;C&gt;",synthetic:false,types:["ng_curve::affine::Point"]},{text:"impl&lt;I:&nbsp;<a class=\"trait\" href=\"ng_field/arith/trait.Scalar.html\" title=\"trait ng_field::arith::Scalar\">Scalar</a>, C:&nbsp;<a class=\"trait\" href=\"ng_curve/trait.Curve.html\" title=\"trait ng_curve::Curve\">Curve</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;I&gt; for <a class=\"struct\" href=\"ng_curve/struct.JacobianPoint.html\" title=\"struct ng_curve::JacobianPoint\">Point</a>&lt;C&gt;",synthetic:false,types:["ng_curve::jacobian::Point"]},];
implementors["ng_field"] = [{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a> for <a class=\"struct\" href=\"ng_field/struct.FieldElement.html\" title=\"struct ng_field::FieldElement\">FieldElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::element::FieldElement"]},{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"struct\" href=\"ng_field/struct.FieldElement.html\" title=\"struct ng_field::FieldElement\">FieldElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::element::FieldElement"]},{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a> for <a class=\"struct\" href=\"ng_field/struct.MontgomeryElement.html\" title=\"struct ng_field::MontgomeryElement\">MontgomeryElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::mont::MontgomeryElement"]},{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"struct\" href=\"ng_field/struct.MontgomeryElement.html\" title=\"struct ng_field::MontgomeryElement\">MontgomeryElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::mont::MontgomeryElement"]},];
implementors["ng_polynomial"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"ng_field/field/trait.FieldValue.html\" title=\"trait ng_field::field::FieldValue\">FieldValue</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a> for <a class=\"struct\" href=\"ng_polynomial/struct.Polynomial.html\" title=\"struct ng_polynomial::Polynomial\">Polynomial</a>&lt;T&gt;",synthetic:false,types:["ng_polynomial::Polynomial"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"ng_field/field/trait.FieldValue.html\" title=\"trait ng_field::field::FieldValue\">FieldValue</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;T&gt; for <a class=\"struct\" href=\"ng_polynomial/struct.Polynomial.html\" title=\"struct ng_polynomial::Polynomial\">Polynomial</a>&lt;T&gt;",synthetic:false,types:["ng_polynomial::Polynomial"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
