(function() {var implementors = {};
implementors["bigint"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U128.html\" title=\"struct bigint::uint::U128\">U128</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U128.html\" title=\"struct bigint::uint::U128\">U128</a>",synthetic:false,types:["bigint::uint::U128"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U256.html\" title=\"struct bigint::uint::U256\">U256</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U256.html\" title=\"struct bigint::uint::U256\">U256</a>",synthetic:false,types:["bigint::uint::U256"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"bigint/uint/struct.U512.html\" title=\"struct bigint::uint::U512\">U512</a>&gt; for <a class=\"struct\" href=\"bigint/uint/struct.U512.html\" title=\"struct bigint::uint::U512\">U512</a>",synthetic:false,types:["bigint::uint::U512"]},];
implementors["ng_field"] = [{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"ng_field/struct.FieldElement.html\" title=\"struct ng_field::FieldElement\">FieldElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::element::FieldElement"]},{text:"impl&lt;F:&nbsp;<a class=\"trait\" href=\"ng_field/trait.Field.html\" title=\"trait ng_field::Field\">Field</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a> for <a class=\"struct\" href=\"ng_field/struct.MontgomeryElement.html\" title=\"struct ng_field::MontgomeryElement\">MontgomeryElement</a>&lt;F&gt;",synthetic:false,types:["ng_field::mont::MontgomeryElement"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
