[package]
name = "ng-uint"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
bigint = { version = "4", features = ["std"] }
ng-field = { path = "../field" }

[dev-dependencies]
quickcheck = "0.7"
