[package]
name = "ng-seck256p1"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
ng-uint = { path = "../../uint-field" }
ng-field = { path = "../../field" }
ng-curve = { path = "../../curve" }
bigint = "4"